### ISSUE TITLE
Patching a map with different keys

### ISSUE THREAD

**Issue by fdorothy** [olafura/json_diff_ex#1]
I'm not sure if this is supported, but I tried calculating a diff for two maps with different keys. The diff produced something, but applying the patch caused a CaseClauseError.

> 
> iex(9)> p = JsonDiffEx.diff(%{"foo" => 1}, %{"bar" => 3})
> %{"bar" => [3], "foo" => [1, 0, 0]}
> iex(10)> JsonDiffEx.patch(%{"foo" => 1}, p)
> ** (CaseClauseError) no case clause matching: [1, 0, 0]
>              lib/json_diff_ex.ex:244: anonymous fn/3 in JsonDiffEx.do_patch/2
>     (elixir) lib/map.ex:362: Map.update/4
>     (stdlib) lists.erl:1262: :lists.foldl/3

I was expected this to produce a map like %{"foo" => 1, "bar" => 3}. Is this not supported?

**Comment by olafura** [comment]
I'll look into that, thanks for the error report ;)
