### ISSUE TITLE
issue with scientific notation equality

### ISSUE THREAD

**Issue by mikeni** [olafura/json_diff_ex#12]
JsonDiffEx.diff(%{a: 2100}, %{a: 2.1e3})
%{a: [2100, 2.1e3]}

**Comment by olafura** [comment]
Interesting

**Comment by olafura** [comment]
One is a float and one is an integer, I'm just wondering if I should add an option to have a more lenient matcher.

**Comment by mikeni** [comment]
I think it would be useful, I am diffing maps and saving as jsonb, one issue I ran into (I think) is postgres jsonb has its own type (maybe decimal?) so if I save floats, it comes up something different.  Then I am diffing an elixir map with floats to something else, sometimes integer if converted.

**Comment by mikeni** [comment]
currently I am taking the Ecto map type and running it through

`
  def map_float_values(map) do
    Enum.reduce(map, %{}, fn({k, v}, acc) -> 
      cond do
        is_number(v) -> Map.put(acc, k, v / 1)
        is_map(v) -> Map.put(acc, k, map_float_values(v))
        true -> acc
      end
    end)
  end
`

**Comment by olafura** [comment]
If you want to take a stab at it it's this line:
https://github.com/olafura/json_diff_ex/blob/master/lib/json_diff_ex.ex#L136

You would just pass options into all the do_diff, which would be a keyword list:
https://www.djm.org.uk/posts/elixir-keyword-lists-function-parameters/

Which would determine if you were using `==` or `===` ;)

**Comment by mikeni** [comment]
submitted a PR, i just did weak equality, all or nothing, for the scalar values, I think, in the future you should be able to customize which type of equality you want for each type

**Comment by olafura** [comment]
I was testing that a bit I think it's only number that can be equal with `==` though I would have to do an exhaustive check :)

**Comment by olafura** [comment]
Thank you for the patch and opening this issue, since I think other people are going to have similar experience ;)

**Comment by olafura** [comment]
There is a new version you can use now ;)

**Comment by mikeni** [comment]
@olafura thanks!

**Comment by mikeni** [comment]
still have an issue with this, need a softened equality for List.myers_difference
pry(2)> l1
[%{"1" => 4, "2" => 2}]
pry(3)> l2
[%{"1" => 4.0, "2" => 2}]
List.myers_difference(l1, l2)
[del: [%{"1" => 4, "2" => 2}], ins: [%{"1" => 4.0, "2" => 2}]]
