### ISSUE TITLE
strict_equality doesn't work for array comparison due to List.myers_difference

### ISSUE THREAD

**Issue by mikeni** [olafura/json_diff_ex#15]
still have an issue with this, need a softened equality for List.myers_difference
pry(2)> l1
[%{"1" => 4, "2" => 2}]
pry(3)> l2
[%{"1" => 4.0, "2" => 2}]
List.myers_difference(l1, l2)
[del: [%{"1" => 4, "2" => 2}], ins: [%{"1" => 4.0, "2" => 2}]]

**Comment by olafura** [comment]
So if I do:
```
l1 = %{"a" => [%{"1" => 4, "2" => 2}]}
l2 = %{"a" => [%{"1" => 4.0, "2" => 2}]}
JsonDiffEx.diff(l1, l2, strict_equality: false)
```
I get:
```
%{"a" => %{"0" => nil, "_t" => "a"}}
```
Which is probably the problem you are getting. This is fixable ;)

**Comment by olafura** [comment]
Open again if what you are describing is something else ;)

**Comment by olafura** [comment]
Published ;)
