### ISSUE TITLE
nil values are dropped when patching?

### ISSUE THREAD

**Issue by jordan0day** [olafura/json_diff_ex#18]
I noticed that a map with a key-value pair where the value is null is having the key dropped after patching. I thought maybe this was the behavior of `jsondiffpatch` but I verified that `jsondiffpatch` seems to preserve the null fields:

```JavaScript
const jsondiffpatch = require('jsondiffpatch');
obj1 = {name: "original", should_be_nil: null};
obj2 = {name: "changed", should_be_nil: null};
var delta = jsondiffpatch.diff(obj1, obj2);
> { name: [ 'original', 'changed' ] }
var patched = jsondiffpatch.patch(obj1, delta);
> { name: 'original', should_be_nil: null }
```

```Elixir
obj1 = %{"name" => "original", "should_be_nil" => nil}
obj2 = %{"name" => "changed", "should_be_nil" => nil}

diff = JsonDiffEx.diff(obj1, obj2)
> %{"name" => ["original", "changed"]}
patched = JsonDiffEx.patch(obj1, diff)
> %{"name" => "changed"}
```

Curious if this is intentional or a bug?

Edit: I guess I should add I see in https://github.com/olafura/json_diff_ex/blob/master/lib/json_diff_ex.ex#L265 where's it dropping the fields with the nil values, so I figured maybe this was intentional?

**Comment by olafura** [comment]
@jordan0day This is just me being silly. If you change https://github.com/olafura/json_diff_ex/blob/master/lib/json_diff_ex.ex#L262 to return an atom like `:interal_atom_to_filter_this_item_out`. And make sure that there are no others that are returning nil that is supposed to use this filter. I think it's only for deleting.

**Comment by jordan0day** [comment]
Submitted #19 to deal with this.

**Comment by olafura** [comment]
Thank you for the three PRs, it's been really helpful. I published a new version on hex.

**Comment by jordan0day** [comment]
Thanks for the great library!
