### ISSUE TITLE
About map traverse order

### ISSUE THREAD

**Issue by tinglei8** [olafura/json_diff_ex#37]
The spec for patching array says:

delta = {
  _t: 'a',
  index1: innerDelta1,
  index2: innerDelta2,
  index5: innerDelta5
}

the delta is a map and its correctness depends on correct traverse order of the delta map data.

How do json_diff_ex ensures the map traverse order when patching is the same as when diffing? elixir won't guarantee it as far as I know.

Regards,
Lei

**Comment by tinglei8** [comment]
I see, the array diffs are sorted and processing delete/move first, then adding. Closing this.

**Comment by olafura** [comment]
@tinglei8 Thanks for the question, sorry I was just away so I couldn't respond. I'm glad you figured it out.
