### ISSUE TITLE
Infinite loop when patch index in list is > 9

### ISSUE THREAD

**Issue by mxgrn** [olafura/json_diff_ex#4]
First of all, many thanks for this library! I plan to greatly decrease my client-server data volume with it.

Here's a bug I came across (sorry I didn't have a moment to go deeper myself):

This data:
```
%{"cards" => [%{"foo" => true}, %{"foo" => true}, %{"foo" => true}, %{"foo" => true}, %{"foo" => true}, %{"foo" => true}, %{"foo" => true}, %{"foo" => true}, %{"foo" => true}, %{"foo" => true}, %{"foo" => true}, %{"foo" => true}]}
```

gets successfully patched with this patch:

```
%{"cards" => %{"0" => %{"foo" => [true, false]}, "_t" => "a"}}
```

However, as soon as I change "0" to "10" (or any number higher than 9) in the patch:

```
%{"cards" => %{"10" => %{"foo" => [true, false]}, "_t" => "a"}}
```

 it seemingly goes into an infinite loop.

**Comment by mxgrn** [comment]
The key place seems to be this line: 

https://github.com/olafura/json_diff_ex/blob/master/lib/json_diff_ex.ex#L227

The problem is that `si` is built as <<i + 48>>, which in case of `i == 10` becomes ":", not "10". While the diff's key is exactly "10". This causes that those keys in `diff2` get never emptied, and the `do_patch_list` function goes into infinite recursion.

Not sure what's the cleanest way to solve it - ideas?

**Comment by olafura** [comment]
Thank you for the bug report. Will hopefully find some time tomorrow to look at it

**Comment by olafura** [comment]
Thank you again for the bug report, I was trying to do something smart to gain some speed but of course I didn't think it through well enough :)
