### ISSUE TITLE
Crashes when something in an array changes order and content

### ISSUE THREAD

**Issue by MarkNijhof** [olafura/json_diff_ex#6]
Is this a known issue or should I investigate?

old = %{"id" => "1", "orders" => [ %{"id" => "12", "status" => "received", "something" => "else" }, %{"id" => "13", "status" => "shipped", "something" => "blah"} ] }

new = %{"id" => "1", "orders" => [ %{"id" => "13", "status" => "shipped", "something" => "blah" }, %{"id" => "12", "status" => "sent", "something" => "else"} ] }

JsonDiffEx.diff(old, new)

** (CaseClauseError) no case clause matching: {:ok, ["", 0, 3]}
    (json_diff_ex) lib/json_diff_ex.ex:82: JsonDiffEx.all_checked/2
    (json_diff_ex) lib/json_diff_ex.ex:128: JsonDiffEx.do_diff/2
    (json_diff_ex) lib/json_diff_ex.ex:157: anonymous fn/3 in JsonDiffEx.do_diff/2
          (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
          (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (json_diff_ex) lib/json_diff_ex.ex:153: JsonDiffEx.do_diff/2
    (json_diff_ex) lib/json_diff_ex.ex:179: JsonDiffEx.diff/2

{:json_diff_ex, "~> 0.5.3"}

**Comment by MarkNijhof** [comment]
hehe I just noticed that I fixed this once before, but was probably to lazy to submit an issue.

If you change https://github.com/olafura/json_diff_ex/blob/master/lib/json_diff_ex.ex#L84 :error into an _ then it behaves as expected.

**Comment by olafura** [comment]
Fixed ;)

**Comment by MarkNijhof** [comment]
Thanks!
